name: 自动同步和更新 README

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      UPSTREAM_REPO: https://github.com/aazooo/zjmf.git
      TARGET_BRANCH: main
      USERNAME_PLACEHOLDER: aazooo
      YOUR_USERNAME: feiyu201

    steps:
    - name: 检出仓库
      uses: actions/checkout@v2

    - name: 设置 Git 用户信息
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"

    - name: 同步上游仓库
      run: |
        git remote add upstream $UPSTREAM_REPO
        git fetch upstream
        git merge upstream/$TARGET_BRANCH --allow-unrelated-histories -m "合并上游更改"
        git push

    - name: 在 README.md 中替换 $USERNAME_PLACEHOLDER 为 $YOUR_USERNAME
      run: sed -i "s/$USERNAME_PLACEHOLDER/$YOUR_USERNAME/g" README.md

    - name: 提交并推送更改到你的仓库
      run: |
        git add README.md
        git commit -m "使用我的用户名更新 README.md"
        git push https://$GITHUB_ACTOR:$PAT_TOKEN@github.com/$GITHUB_REPOSITORY.git HEAD:$GITHUB_REF
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
