name: 同步仓库
on:
  schedule:
    - cron: '0 1 * * *' # 按UTC时间每天凌晨1点执行
  workflow_dispatch: # 允许手动触发

jobs:
  sync-task: # 同步任务
    runs-on: ubuntu-latest
    steps:
    - name: 检出基础仓库
      uses: actions/checkout@v2
      with:
        repository: aazooo/zjmf.git
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0 # 获取全部历史以便比较

    - name: 创建新分支
      run: |
        git checkout -b new-branch

    - name: 检查变动
      id: check-changes # 检查变动
      run: |
        git fetch origin
        CHANGES=$(git diff --name-only origin/master...master)
        if [ -n "$CHANGES" ]; then
          echo "::set-output name=has_changes::true"
        else
          echo "::set-output name=has_changes::false"
        fi

    - name: 同步并推送变动
      if: steps.check-changes.outputs.has_changes == 'true'
      run: |
        git config user.name ${{ secrets.USER_NAME }}
        git config user.email ${{ secrets.USER_EMAIL }}
        git remote set-url origin ${{ github.event.repository.clone_url }}
        git remote add upstream https://github.com/aazooo/zjmf.git
        git pull upstream master
        sed -i 's/aazooo/feiyu201/g' README.md
        git commit -am "同步变动并更新README"
        git push --set-upstream origin new-branch
